.TH "contextFree.parser.State" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.parser.State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP ()"
.br
.RI "\fIconstructor state 0 \fP"
.ti -1c
.RI "\fBState\fP (int i)"
.br
.RI "\fIconstructor state i-th, with empty list productions \fP"
.ti -1c
.RI "\fBState\fP (int i, List< \fBIndexedProduction\fP > c)"
.br
.RI "\fIconstructor state i-th, whit list production c \fP"
.ti -1c
.RI "\fBState\fP (int i, List< \fBIndexedProduction\fP > c, Hashtable< String, Integer > table)"
.br
.RI "\fIconstructor state i-th, whit list production c and list of lookahead \fP"
.ti -1c
.RI "List< \fBIndexedProduction\fP > \fBgetItems\fP ()"
.br
.ti -1c
.RI "void \fBsetItems\fP (List< \fBIndexedProduction\fP > Items)"
.br
.ti -1c
.RI "Hashtable< String, Integer > \fBgetShift\fP ()"
.br
.ti -1c
.RI "void \fBsetShift\fP (Hashtable< String, Integer > shift)"
.br
.ti -1c
.RI "int \fBgetIndex\fP ()"
.br
.ti -1c
.RI "void \fBsetIndex\fP (int index)"
.br
.ti -1c
.RI "Integer \fBgotoStateIndex\fP (String simbol)"
.br
.RI "\fIReturn the index of the state shifted with a specific simbol\&. \fP"
.ti -1c
.RI "List< \fBIndexedProduction\fP > \fBgetKernels\fP ()"
.br
.RI "\fIreturn one list<IndexedProduction> with the kernel of a state \fP"
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "List< \fBIndexedProduction\fP > \fBitems\fP"
.br
.ti -1c
.RI "Hashtable< String, Integer > \fBshift\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file State\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBcontextFree\&.parser\&.State\&.State\fP (inti)"

.PP
constructor state i-th, with empty list productions \fBParameters:\fP
.RS 4
\fIindex\fP of state 
.RE
.PP

.PP
Definition at line 26 of file State\&.java\&.
.SS "\fBcontextFree\&.parser\&.State\&.State\fP (inti, List< \fBIndexedProduction\fP >c)"

.PP
constructor state i-th, whit list production c \fBParameters:\fP
.RS 4
\fIindex\fP of state 
.br
\fIList\fP production 
.RE
.PP

.PP
Definition at line 37 of file State\&.java\&.
.SS "\fBcontextFree\&.parser\&.State\&.State\fP (inti, List< \fBIndexedProduction\fP >c, Hashtable< String, Integer >table)"

.PP
constructor state i-th, whit list production c and list of lookahead \fBParameters:\fP
.RS 4
\fIindex\fP of state 
.br
\fIList\fP production 
.br
\fIList\fP of lookahead 
.RE
.PP

.PP
Definition at line 49 of file State\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "List<\fBIndexedProduction\fP> \fBcontextFree\&.parser\&.State\&.getKernels\fP ()"

.PP
return one list<IndexedProduction> with the kernel of a state \fBReturns:\fP
.RS 4
the kernels prodaction 
.RE
.PP
\fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Definition at line 97 of file State\&.java\&.
.SS "Integer \fBcontextFree\&.parser\&.State\&.gotoStateIndex\fP (Stringsimbol)"

.PP
Return the index of the state shifted with a specific simbol\&. .PP
.nf
  @param simbol the shift simbol
.fi
.PP
 
.PP
\fBReturns:\fP
.RS 4
the index of the state or null 
.RE
.PP

.PP
Definition at line 84 of file State\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
