.TH "contextFree.parser.ParserFactory" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.parser.ParserFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIParser\fP \fBcreateParser\fP ()"
.br
.ti -1c
.RI "static \fBIParser\fP \fBcreateParser\fP (\fBAbstractInputParser\fP parser)"
.br
.ti -1c
.RI "static \fBIParser\fP \fBcreateParser\fP (\fBIGrammar\fP grammar)"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger(ParserFactory\&.class\&.getName())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ParserFactory\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
