.TH "contextFree.scanner.LR1" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.scanner.LR1 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBsetGrammar\fP (\fBIGrammar\fP gram)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBIGrammar\fP \fBgrammatica\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file LR1\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
