.TH "contextFree.scanner.ScannerFactory" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.scanner.ScannerFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIScanner\fP \fBcreateParser\fP ()  throws Exception"
.br
.ti -1c
.RI "static \fBIScanner\fP \fBcreateParser\fP (\fBAbstractInputParser\fP parser)  throws Exception"
.br
.ti -1c
.RI "static \fBIScanner\fP \fBcreateParser\fP (\fBIGrammar\fP grammar)  throws Exception "
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger(ScannerFactory\&.class\&.getName())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 22 of file ScannerFactory\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
