.TH "contextFree.scanner.IScanner" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.scanner.IScanner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcontextFree\&.scanner\&.LR0\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetGrammar\fP (\fBIGrammar\fP gram)"
.br
.ti -1c
.RI "int \fBinit\fP ()  throws Exception"
.br
.ti -1c
.RI "\fBIGrammar\fP \fBgetGrammar\fP ()"
.br
.ti -1c
.RI "boolean \fBisAmbiguos\fP ()"
.br
.ti -1c
.RI "\fBAutoma\fP \fBgetAutoma\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file IScanner\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
