.TH "contextFree.grammar.ContextFreeGrammar" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.grammar.ContextFreeGrammar \- 
.PP
Define a context-free grammar type\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContextFreeGrammar\fP (String ass, List< \fBProduction\fP > prod)"
.br
.ti -1c
.RI "\fBContextFreeGrammar\fP (String ass, List< \fBProduction\fP > prod, List< String > V, List< String > T)"
.br
.ti -1c
.RI "List< String > \fBgetV\fP ()"
.br
.RI "\fIGet non-terminal symbols list\&. \fP"
.ti -1c
.RI "void \fBsetV\fP (List< String > v)"
.br
.RI "\fISet the list of non-terminal symbols\&. \fP"
.ti -1c
.RI "List< String > \fBgetT\fP ()"
.br
.RI "\fIGet terminal symbols list\&. \fP"
.ti -1c
.RI "void \fBsetT\fP (List< String > e)"
.br
.RI "\fISet the list of terminal symbols\&. \fP"
.ti -1c
.RI "List< \fBProduction\fP > \fBgetP\fP ()"
.br
.RI "\fIGet production list\&. \fP"
.ti -1c
.RI "void \fBsetP\fP (List< \fBProduction\fP > p)"
.br
.RI "\fISet the produciton list\&. \fP"
.ti -1c
.RI "String \fBgetS\fP ()"
.br
.RI "\fIGet the axioms\&. \fP"
.ti -1c
.RI "void \fBsetS\fP (String s)"
.br
.RI "\fISet the axioms for the grammar\&. \fP"
.ti -1c
.RI "Set< String >[] \fBgetFirst\fP ()"
.br
.RI "\fIGet the list of first for the grammar\&. \fP"
.ti -1c
.RI "Set< String > \fBgetFirst\fP (String A)"
.br
.RI "\fII spent a character returns the first list associated to it\&. \fP"
.ti -1c
.RI "Set< String >[] \fBgetFollow\fP ()"
.br
.RI "\fII spent a character returns the Follow list associated to it\&. \fP"
.ti -1c
.RI "void \fBnullo\fP ()"
.br
.RI "\fIpopulation structure Bolean [] null defined in class grammar, it has the same size of V\&. \fP"
.ti -1c
.RI "void \fBfirst\fP ()"
.br
.RI "\fIPopulate structure in Set<String>[]first for each non-terminal V, using a structure of type Set to avoid duplication\&. \fP"
.ti -1c
.RI "void \fBfollow\fP ()"
.br
.RI "\fIPopulation structure in Set <String> [] first for each non-terminal V, using a structure of type Set to avoid duplication\&. \fP"
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "String \fBtoOneLineString\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< String > \fBV\fP"
.br
.ti -1c
.RI "List< String > \fBT\fP"
.br
.ti -1c
.RI "List< \fBProduction\fP > \fBP\fP"
.br
.ti -1c
.RI "String \fBS\fP"
.br
.ti -1c
.RI "boolean[] \fBnullo\fP"
.br
.ti -1c
.RI "Set< String >[] \fBfirst\fP"
.br
.ti -1c
.RI "Set< String >[] \fBfollow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define a context-free grammar type\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 15 of file ContextFreeGrammar\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void contextFree\&.grammar\&.ContextFreeGrammar\&.first ()"

.PP
Populate structure in Set<String>[]first for each non-terminal V, using a structure of type Set to avoid duplication\&. \fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Definition at line 181 of file ContextFreeGrammar\&.java\&.
.SS "void contextFree\&.grammar\&.ContextFreeGrammar\&.follow ()"

.PP
Population structure in Set <String> [] first for each non-terminal V, using a structure of type Set to avoid duplication\&. \fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Definition at line 249 of file ContextFreeGrammar\&.java\&.
.SS "Set<String> [] \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getFirst\fP ()"

.PP
Get the list of first for the grammar\&. \fBReturns:\fP
.RS 4
the first list\&. 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 90 of file ContextFreeGrammar\&.java\&.
.SS "Set<String> \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getFirst\fP (StringA)"

.PP
I spent a character returns the first list associated to it\&. \fBParameters:\fP
.RS 4
\fISimbol\fP not-Terminal A 
.RE
.PP
\fBReturns:\fP
.RS 4
First(A) 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 101 of file ContextFreeGrammar\&.java\&.
.SS "Set<String> [] \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getFollow\fP ()"

.PP
I spent a character returns the Follow list associated to it\&. \fBParameters:\fP
.RS 4
\fISimbol\fP not-terminal A 
.RE
.PP
\fBReturns:\fP
.RS 4
Follow(A) 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 110 of file ContextFreeGrammar\&.java\&.
.SS "List<\fBProduction\fP> \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getP\fP ()"

.PP
Get production list\&. \fBReturns:\fP
.RS 4
a list of production objects\&. 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 71 of file ContextFreeGrammar\&.java\&.
.SS "String \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getS\fP ()"

.PP
Get the axioms\&. \fBReturns:\fP
.RS 4
the axioms 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 81 of file ContextFreeGrammar\&.java\&.
.SS "List<String> \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getT\fP ()"

.PP
Get terminal symbols list\&. \fBReturns:\fP
.RS 4
a list of string with terminal symbol 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 61 of file ContextFreeGrammar\&.java\&.
.SS "List<String> \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.getV\fP ()"

.PP
Get non-terminal symbols list\&. \fBReturns:\fP
.RS 4
a list of string with non-terminal symbol 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 51 of file ContextFreeGrammar\&.java\&.
.SS "void contextFree\&.grammar\&.ContextFreeGrammar\&.nullo ()"

.PP
population structure Bolean [] null defined in class grammar, it has the same size of V\&. one element is said to null if every component of the expression of the production will be 'null\&. 
.PP
\fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Definition at line 121 of file ContextFreeGrammar\&.java\&.
.SS "void \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.setP\fP (List< \fBProduction\fP >p)"

.PP
Set the produciton list\&. \fBParameters:\fP
.RS 4
\fIp\fP the list of productions that must be setted\&. 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 76 of file ContextFreeGrammar\&.java\&.
.SS "void \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.setS\fP (Strings)"

.PP
Set the axioms for the grammar\&. \fBParameters:\fP
.RS 4
\fIs\fP the axioms\&. 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 86 of file ContextFreeGrammar\&.java\&.
.SS "void \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.setT\fP (List< String >e)"

.PP
Set the list of terminal symbols\&. \fBParameters:\fP
.RS 4
\fIe\fP the list of terminal 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 66 of file ContextFreeGrammar\&.java\&.
.SS "void \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.setV\fP (List< String >v)"

.PP
Set the list of non-terminal symbols\&. \fBParameters:\fP
.RS 4
\fIv\fP the list of non-terminal 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 56 of file ContextFreeGrammar\&.java\&.
.SS "String \fBcontextFree\&.grammar\&.ContextFreeGrammar\&.toOneLineString\fP ()"
\fBReturns:\fP
.RS 4
the grammar string formatted in one line\&. 
.RE
.PP

.PP
Implements \fBcontextFree\&.grammar\&.IGrammar\fP\&.
.PP
Definition at line 337 of file ContextFreeGrammar\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
