.TH "contextFree.grammar.GRAMMAR_TYPE" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contextFree.grammar.GRAMMAR_TYPE \- 
.PP
Specify the type of a grammar\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCONTEXT_FREE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specify the type of a grammar\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 7 of file GRAMMAR_TYPE\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
