.TH "error.ERROR_TYPE" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.ERROR_TYPE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBINPUT_FILE\fP"
.br
.ti -1c
.RI "\fBINVALID_GRAMMAR\fP"
.br
.ti -1c
.RI "\fBFILE_EXTENSION\fP"
.br
.ti -1c
.RI "\fBFILE_FORMAT\fP"
.br
.ti -1c
.RI "\fBLOOKAHEAD_GENERATION_ERROR\fP"
.br
.ti -1c
.RI "\fBLOOKAHEAD_PROPAGATION_ERROR\fP"
.br
.ti -1c
.RI "\fBTABLE_CONSTRUCTION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ERROR_TYPE\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
