.TH "error.ErrorManager" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.ErrorManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmanage\fP (\fBERROR_TYPE\fP type)"
.br
.ti -1c
.RI "static void \fBmanage\fP (\fBERROR_TYPE\fP type, Exception e)  throws Exception"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger(ErrorManager\&.class\&.getName())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ErrorManager\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
