.TH "GenericFileFilter" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericFileFilter \- 
.PP
Filter the file type for the file chooser\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FileFilter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericFileFilter\fP (String descrizione, String estensione)"
.br
.ti -1c
.RI "boolean \fBaccept\fP (File f)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBdescrizione\fP"
.br
.ti -1c
.RI "String \fBfinale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filter the file type for the file chooser\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 10 of file GenericFileFilter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
