.TH "HomeGui" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeGui \- 
.PP
The gui access\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHomeGui\fP ()  throws FileNotFoundException, Exception "
.br
.RI "\fIInitialize GUI component and start the process\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.RI "\fILaunch the application\&. \fP"
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "TextArea \fBautomaText\fP"
.br
.ti -1c
.RI "FileFilter \fBfourlineFileFilter\fP"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger(HomeGui\&.class\&.getName())"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperazioneApri\fP ()  throws FileNotFoundException, Exception "
.br
.ti -1c
.RI "void \fBstartProcess\fP (String path)  throws FileNotFoundException, Exception "
.br
.RI "\fIStart the parsing of grammar file and create result file\&. \fP"
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.RI "\fISave operation\&. \fP"
.ti -1c
.RI "DefaultMutableTreeNode \fBastMethod\fP (\fBParserProgram\fP parserProgram)  throws Exception "
.br
.RI "\fICreate the AST\&. \fP"
.ti -1c
.RI "void \fBwriteToXml\fP (DefaultMutableTreeNode root)  throws FileNotFoundException "
.br
.RI "\fIStore an AST into xml file named 'AST\&.xml'\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "JFrame \fBframe\fP"
.br
.ti -1c
.RI "Panel \fBrightPanel\fP"
.br
.ti -1c
.RI "String \fBfilePath\fP"
.br
.ti -1c
.RI "JButton \fBstartParsing\fP"
.br
.ti -1c
.RI "TextArea \fBleftPanel\fP"
.br
.ti -1c
.RI "JTree \fBtree\fP"
.br
.ti -1c
.RI "JFileChooser \fBapriFileChooser\fP"
.br
.ti -1c
.RI "FileFilter \fBtxtFileFilter\fP"
.br
.ti -1c
.RI "FileFilter \fBonelineFileFilter\fP"
.br
.ti -1c
.RI "JTextField \fBinput\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final long \fBserialVersionUID\fP = 1L"
.br
.in -1c
.SH "Detailed Description"
.PP 
The gui access\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 51 of file HomeGui\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHomeGui\&.HomeGui\fP ()  throws FileNotFoundException, Exception "

.PP
Initialize GUI component and start the process\&. \fBExceptions:\fP
.RS 4
\fIException\fP 
.br
\fIFileNotFoundException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 86 of file HomeGui\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "DefaultMutableTreeNode \fBHomeGui\&.astMethod\fP (\fBParserProgram\fPparserProgram)  throws Exception \fC [private]\fP"

.PP
Create the AST\&. \fBParameters:\fP
.RS 4
\fIparser\fP the object that rappresent 'Result\&.txt' 
.RE
.PP
\fBReturns:\fP
.RS 4
DefaultMutableTreeNode root of AST 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 352 of file HomeGui\&.java\&.
.SS "void \fBHomeGui\&.initialize\fP ()\fC [private]\fP"

.PP
Save operation\&. Initialize the contents of the frame\&. When clicked parse 'Result\&.txt' file and create the AST\&. 
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino
.RE
.PP

.PP
Definition at line 176 of file HomeGui\&.java\&.
.SS "void \fBHomeGui\&.startProcess\fP (Stringpath)  throws FileNotFoundException, Exception \fC [private]\fP"

.PP
Start the parsing of grammar file and create result file\&. \fBParameters:\fP
.RS 4
\fIpath\fP the path of grammar file (ex\&. grammar\&.4l) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.br
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 127 of file HomeGui\&.java\&.
.SS "void \fBHomeGui\&.writeToXml\fP (DefaultMutableTreeNoderoot)  throws FileNotFoundException \fC [private]\fP"

.PP
Store an AST into xml file named 'AST\&.xml'\&. \fBParameters:\fP
.RS 4
\fIroot\fP the root of AST 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 380 of file HomeGui\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
