.TH "inputParser.InputParserFactory" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputParser.InputParserFactory \- 
.PP
Abstract \fBInputParserFactory\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBinputParser\&.ConcreteParserFactory\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBAbstractInputParser\fP \fBfactoryMethod\fP (String in)"
.br
.RI "\fIReturn different object instance based on the extension\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Abstract \fBInputParserFactory\fP\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 8 of file InputParserFactory\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract \fBAbstractInputParser\fP \fBinputParser\&.InputParserFactory\&.factoryMethod\fP (Stringin)\fC [protected, pure virtual]\fP"

.PP
Return different object instance based on the extension\&. \fBParameters:\fP
.RS 4
\fIthe\fP path of file to parse\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
FourLineInputParser(input) instance if the file extension is '\&.4l',
.br
 SingleLineInputParser(input) instance if the file extension is '\&.1l',
.br
 LRInputParser(in) instance if the file extension is '\&.txt', null otherwise\&. 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Implemented in \fBinputParser\&.ConcreteParserFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
