.TH "inputParser.SplitInSymbols" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputParser.SplitInSymbols \- 
.PP
Split the input string in symbols list\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplitInSymbols\fP (String ob, List< String > res, List< String > symb)"
.br
.RI "\fIConstructor with input String\&. \fP"
.ti -1c
.RI "String \fBgetObj\fP ()"
.br
.ti -1c
.RI "void \fBsetObj\fP (String obj)"
.br
.ti -1c
.RI "List< String > \fBgetResult\fP ()"
.br
.ti -1c
.RI "void \fBsetResult\fP (List< String > result)"
.br
.ti -1c
.RI "List< String > \fBgetSymbols\fP ()"
.br
.ti -1c
.RI "void \fBsetSymbols\fP (List< String > symbols)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "List< String > \fBSymbols\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBobj\fP"
.br
.ti -1c
.RI "List< String > \fBresult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Split the input string in symbols list\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 12 of file SplitInSymbols\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "inputParser\&.SplitInSymbols\&.SplitInSymbols (Stringob, List< String >res, List< String >symb)"

.PP
Constructor with input String\&. \fBParameters:\fP
.RS 4
\fIob\fP the input string 
.br
\fIres\fP where the result are stored 
.br
\fIsymb\fP the list of allowed symbols 
.RE
.PP

.PP
Definition at line 23 of file SplitInSymbols\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
