.TH "inputParser.SingleLineInputParser" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputParser.SingleLineInputParser \- 
.PP
Parse a single line grammar format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinputParser\&.AbstractInputParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSingleLineInputParser\fP (String in)"
.br
.ti -1c
.RI "\fBIGrammar\fP \fBparse\fP ()  throws Exception "
.br
.ti -1c
.RI "\fBIGrammar\fP \fBparseString\fP (String input)  throws Exception "
.br
.RI "\fIExecute the parse operation on the object\&. \fP"
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBS\fP"
.br
.ti -1c
.RI "String \fBfile\fP"
.br
.ti -1c
.RI "List< \fBProduction\fP > \fBP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parse a single line grammar format\&. 

ex (file\&.1l): S::= { S: TE | +TE; T: FT | xFT; E : eps; F: a | (E)} 
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 23 of file SingleLineInputParser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIGrammar\fP \fBinputParser\&.SingleLineInputParser\&.parse\fP ()  throws Exception \fC [virtual]\fP"
\fBReturns:\fP
.RS 4
ContextFreeGrammar instance if the string is correctly formatted, null otherwise\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Implements \fBinputParser\&.AbstractInputParser\fP\&.
.PP
Definition at line 45 of file SingleLineInputParser\&.java\&.
.SS "\fBIGrammar\fP \fBinputParser\&.SingleLineInputParser\&.parseString\fP (Stringinput)  throws Exception "

.PP
Execute the parse operation on the object\&. \fBParameters:\fP
.RS 4
\fIinput\fP grammar file 
.RE
.PP
\fBReturns:\fP
.RS 4
ContextFreeGrammar instance if the string is correctly formatted, null otherwise\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP

.PP
Definition at line 66 of file SingleLineInputParser\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
