.TH "inputParser.AbstractInputParser" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputParser.AbstractInputParser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBinputParser\&.FourLineInputParser\fP, \fBinputParser\&.InputParser\fP, \fBinputParser\&.LRInputParser\fP, and \fBinputParser\&.SingleLineInputParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract Object \fBparse\fP ()  throws Exception"
.br
.RI "\fIExecute the parse operation on the object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file AbstractInputParser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract Object \fBinputParser\&.AbstractInputParser\&.parse\fP ()  throws Exception\fC [pure virtual]\fP"

.PP
Execute the parse operation on the object\&. \fBReturns:\fP
.RS 4
the parsing result 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIException\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Implemented in \fBinputParser\&.InputParser\fP, \fBinputParser\&.FourLineInputParser\fP, \fBinputParser\&.SingleLineInputParser\fP, and \fBinputParser\&.LRInputParser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
