.TH "inputParser.FourLineInputParser" 3 "Fri Mar 30 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputParser.FourLineInputParser \- 
.PP
Parse a four line grammar format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBinputParser\&.AbstractInputParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFourLineInputParser\fP (String input)"
.br
.ti -1c
.RI "\fBIGrammar\fP \fBparse\fP ()  throws Exception"
.br
.RI "\fIRead the file \&.4l and creates the object grammar\&. \fP"
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBfile\fP"
.br
.ti -1c
.RI "String \fBA_reader\fP"
.br
.ti -1c
.RI "String \fBV_reader\fP"
.br
.ti -1c
.RI "String \fBT_reader\fP"
.br
.ti -1c
.RI "String \fBP_reader\fP"
.br
.ti -1c
.RI "String[] \fBV_temp\fP"
.br
.ti -1c
.RI "String[] \fBT_temp\fP"
.br
.ti -1c
.RI "String[] \fBP_temp\fP"
.br
.ti -1c
.RI "String[] \fBsingPro\fP"
.br
.ti -1c
.RI "\fBProduction\fP \fBpro\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "List< String > \fBV\fP = null"
.br
.ti -1c
.RI "List< String > \fBT\fP = null"
.br
.ti -1c
.RI "List< \fBProduction\fP > \fBP\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parse a four line grammar format\&. 

ex (file\&.4l): E E, T, P a, +, x, (, ), $ E::=E+T, E::=T, T::=TxP, T::=P, P::=a, P::=(E) 
.PP
\fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Definition at line 26 of file FourLineInputParser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIGrammar\fP \fBinputParser\&.FourLineInputParser\&.parse\fP ()  throws Exception\fC [virtual]\fP"

.PP
Read the file \&.4l and creates the object grammar\&. \fBReturns:\fP
.RS 4
the grammar 
.RE
.PP
\fBAuthor:\fP
.RS 4
Pierluigi Sottile 
.RE
.PP

.PP
Implements \fBinputParser\&.AbstractInputParser\fP\&.
.PP
Definition at line 54 of file FourLineInputParser\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
