.TH "parserProgram.ParserProgram" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parserProgram.ParserProgram \- 
.PP
This class is responsible of the parsing of input string, and stack parsing creation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParserProgram\fP (String in)"
.br
.ti -1c
.RI "\fBParserProgram\fP (\fBIGrammar\fP g, Hashtable< String, List< String >> action, Hashtable< String, List< String >> goTo)"
.br
.ti -1c
.RI "void \fBsetActionTable\fP (Hashtable< String, List< String >> actionTable)"
.br
.ti -1c
.RI "void \fBsetGotoTable\fP (Hashtable< String, List< String >> gotoTable)"
.br
.ti -1c
.RI "Stack< String > \fBgetStack\fP ()"
.br
.ti -1c
.RI "void \fBsetStack\fP (Stack< String > stack)"
.br
.ti -1c
.RI "String \fBgetInput\fP ()"
.br
.ti -1c
.RI "void \fBsetInput\fP (String input)"
.br
.ti -1c
.RI "\fBIGrammar\fP \fBgetGrammar\fP ()"
.br
.ti -1c
.RI "void \fBsetGrammar\fP (\fBIGrammar\fP grammar)"
.br
.ti -1c
.RI "List< \fBHistoryElement\fP > \fBgetHistory\fP ()"
.br
.ti -1c
.RI "\fBRESULT\fP \fBparse\fP ()"
.br
.RI "\fIThe leading method of the class, responsible of the parsing of input string and consequent stack parsing and history creation\&. \fP"
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger(ParserProgram\&.class\&.getName())"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static String \fBreplaceLast\fP (String text, String regex, String replacement)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Stack< String > \fBstack\fP"
.br
.ti -1c
.RI "String \fBsimbol\fP"
.br
.ti -1c
.RI "String \fBinput\fP"
.br
.ti -1c
.RI "\fBIGrammar\fP \fBgrammar\fP"
.br
.ti -1c
.RI "List< \fBHistoryElement\fP > \fBhistory\fP"
.br
.ti -1c
.RI "Hashtable< String, List< String > > \fBactionTable\fP"
.br
.ti -1c
.RI "Hashtable< String, List< String > > \fBgotoTable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is responsible of the parsing of input string, and stack parsing creation\&. 

It also save the parsing chronology\&. It use a Grammar and its Action and Goto table\&. All this operation are executed with \fBparse()\fP method\&. 
.PP
\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 23 of file ParserProgram\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRESULT\fP \fBparserProgram\&.ParserProgram\&.parse\fP ()"

.PP
The leading method of the class, responsible of the parsing of input string and consequent stack parsing and history creation\&. \fBReturns:\fP
.RS 4
RESULT\&.ACCEPT if the string has been accepted, RESULT\&.ERROR if not, RESULT\&.INVALID_ID if the input string is invalid 
.RE
.PP

.PP
Definition at line 109 of file ParserProgram\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
