.TH "parserProgram.HistoryElement" 3 "Wed Mar 21 2012" "Version 1.1" "Context Free LALR1 compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parserProgram.HistoryElement \- 
.PP
This class represent an element of the parsing history\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryElement\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBHistoryElement\fP (String[] stk)"
.br
.RI "\fIConstruct the object with specified parsing stack\&. \fP"
.ti -1c
.RI "\fBHistoryElement\fP (String[] stk, \fBProduction\fP p, String s)"
.br
.RI "\fIConstruct the object with specified parsing stack, production and step\&. \fP"
.ti -1c
.RI "String[] \fBgetStack\fP ()"
.br
.ti -1c
.RI "void \fBsetStack\fP (String[] stack)"
.br
.RI "\fISet the stack\&. \fP"
.ti -1c
.RI "\fBProduction\fP \fBgetProduction\fP ()"
.br
.ti -1c
.RI "void \fBsetProduction\fP (\fBProduction\fP production)"
.br
.RI "\fISet the production\&. \fP"
.ti -1c
.RI "String \fBgetSimbol\fP ()"
.br
.ti -1c
.RI "void \fBsetSimbol\fP (String simbol)"
.br
.RI "\fISet the parsing step\&. \fP"
.ti -1c
.RI "boolean \fBisShift\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String[] \fBstack\fP"
.br
.ti -1c
.RI "\fBProduction\fP \fBproduction\fP"
.br
.ti -1c
.RI "String \fBsimbol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represent an element of the parsing history\&. 

\fBAuthor:\fP
.RS 4
Paolo Pino 
.RE
.PP

.PP
Definition at line 11 of file HistoryElement\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBparserProgram\&.HistoryElement\&.HistoryElement\fP (String[]stk)"

.PP
Construct the object with specified parsing stack\&. \fBParameters:\fP
.RS 4
\fIstk\fP the stack to set\&. 
.RE
.PP

.PP
Definition at line 29 of file HistoryElement\&.java\&.
.SS "\fBparserProgram\&.HistoryElement\&.HistoryElement\fP (String[]stk, \fBProduction\fPp, Strings)"

.PP
Construct the object with specified parsing stack, production and step\&. \fBParameters:\fP
.RS 4
\fIp\fP the production\&. 
.br
\fIs\fP the step\&. 
.br
\fIstk\fP the stack to set\&. 
.RE
.PP

.PP
Definition at line 41 of file HistoryElement\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBProduction\fP \fBparserProgram\&.HistoryElement\&.getProduction\fP ()"
\fBReturns:\fP
.RS 4
the production in the history element 
.RE
.PP

.PP
Definition at line 65 of file HistoryElement\&.java\&.
.SS "String \fBparserProgram\&.HistoryElement\&.getSimbol\fP ()"
\fBReturns:\fP
.RS 4
the history step\&. 
.RE
.PP

.PP
Definition at line 80 of file HistoryElement\&.java\&.
.SS "String [] \fBparserProgram\&.HistoryElement\&.getStack\fP ()"
\fBReturns:\fP
.RS 4
the stack 
.RE
.PP

.PP
Definition at line 50 of file HistoryElement\&.java\&.
.SS "boolean \fBparserProgram\&.HistoryElement\&.isShift\fP ()"
\fBReturns:\fP
.RS 4
true if the history element execute a shift\&. 
.RE
.PP

.PP
Definition at line 94 of file HistoryElement\&.java\&.
.SS "void \fBparserProgram\&.HistoryElement\&.setProduction\fP (\fBProduction\fPproduction)"

.PP
Set the production\&. \fBParameters:\fP
.RS 4
\fIproduction\fP the production to set\&. 
.RE
.PP

.PP
Definition at line 73 of file HistoryElement\&.java\&.
.SS "void \fBparserProgram\&.HistoryElement\&.setSimbol\fP (Stringsimbol)"

.PP
Set the parsing step\&. \fBParameters:\fP
.RS 4
\fIsimbol\fP the parsing step\&. 
.RE
.PP

.PP
Definition at line 87 of file HistoryElement\&.java\&.
.SS "void \fBparserProgram\&.HistoryElement\&.setStack\fP (String[]stack)"

.PP
Set the stack\&. \fBParameters:\fP
.RS 4
\fIstack\fP the stack\&. 
.RE
.PP

.PP
Definition at line 58 of file HistoryElement\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Context Free LALR1 compiler from the source code\&.
