package error;

public enum ERROR_TYPE {
	INPUT_FILE,
	INVALID_GRAMMAR,
	FILE_EXTENSION, FILE_FORMAT,
	LOOKAHEAD_GENERATION_ERROR, LOOKAHEAD_PROPAGATION_ERROR, TABLE_CONSTRUCTION, LALR1_INIT
}
